### PR TITLE
Add more papers

### PR DESCRIPTION
**Pull request by petulla**
Matt,

Here a few additions. I am currently doing a lit review, so there will be more additions. I can leave this PR open for a few weeks.

### CODE REVIEW

**Comment by mathisonian** [comment]
Cool, thanks @petulla! 

I'll leave this open until you say otherwise

**Comment by petulla** [comment]
@mathisonian 

Matt, this is ready when you're ready. I'll make a separate PR focused on visualizing uncertainty.

**Comment by mathisonian** [comment]
This is great  🎉 thanks for the huge contribution! 

Whenever anyone makes a significant PR to one of my repos I invite them to be a collaborator on it, so you should get an invite with push access shortly.

**Comment by petulla** [comment]
Thanks! I cut out a lot of papers I didn't think were so great. But I may be more forthcoming about uncertainty. If you'd like me to add more on any one topic, just let me know. @mathisonian

**Pull request merged**
